### ISSUE TITLE
brak obrazka w sekcji dodatki

### ISSUE THREAD

**Issue by renkobun** [rentha/pizzeriaCDV#6]
hej, zauważyłem, że brakuje obrazka przy sekcji dodatki. trzeba to poprawić.

**Comment by rentha** [comment]
commit 5bc17772045a1866fa80b1a505127db5c59f8a45 naprawia ten błąd

**Comment by rentha** [comment]
5bc17772045a1866fa80b1a505127db5c59f8a45 fixes #6
